In [265]:
#Importando as bibliotecas necessárias e apelidando para facilitar o desenvolvimento 
import pandas as pd

In [266]:
#Fazendo a leitura do arquivo.
df = pd.read_csv(r".\data\dataset_aula1_numpy_pandas.csv")

In [267]:
#Exibe tudo
df

    id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0             1  Montagem          72.62          41.77           111      0
1             2  Usinagem          81.65          34.08           128      0
2             3  Usinagem          68.87          39.44           159      0
3             4  Usinagem          66.84          34.52            98      0
4             5  Usinagem          66.23          31.57            94      0
5             6  Usinagem          64.79          37.09            83      0
6             7  Usinagem          85.02          36.34           106      1
7             8  Inspeção          60.31          33.77           124      0
8             9  Montagem          75.84          29.65            92      0
9            10  Inspeção          68.38          28.93           145      1
10           11  Usinagem          76.31          35.48           149      0
11           12  Inspeção          74.79          33.37           134      0
12           13  Usinagem          76.31          36.51           154      0
13           14  Montagem          63.28          33.71           129      0
14           15  Montagem          64.98          33.24            83      0
15           16  Montagem          81.48          30.50           102      0
16           17  Montagem          79.62          39.68            85      1
17           18  Inspeção          69.80          27.20            91      0
18           19  Inspeção          77.16          47.45            99      0
19           20  Usinagem          73.30          39.77           119      1
20           21  Inspeção          79.77          38.04            91      0
21           22  Usinagem          71.76          35.16            80      0
22           23  Inspeção          74.16          31.93           149      0
23           24  Usinagem          74.69          32.34           123      1
24           25  Usinagem          74.03          32.71           145      1
25           26  Usinagem          75.96          38.70            93      0
26           27  Usinagem          60.80          37.18           159      0
27           28  Montagem          69.37          35.90           122      1
28           29  Montagem          70.28          35.04           103      0
29           30  Inspeção          73.53          32.84            82      0
30           31  Montagem          63.59          42.29           159      1
31           32  Inspeção          68.91          32.66           155      0
32           33  Inspeção          77.62          35.70           108      1
33           34  Inspeção          73.32          32.18           129      1
34           35  Usinagem          78.24          31.93           158      0
35           36  Usinagem          68.47          36.87            87      0
36           37  Inspeção          75.62          30.78           125      1
37           38  Usinagem          78.50          36.39            90      0
38           39  Montagem          76.19          36.54           111      1
39           40  Montagem          68.64          34.88           102      0

In [268]:
#Exibe as 5 primeiras 
df.head()

   id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0            1  Montagem          72.62          41.77           111      0
1            2  Usinagem          81.65          34.08           128      0
2            3  Usinagem          68.87          39.44           159      0
3            4  Usinagem          66.84          34.52            98      0
4            5  Usinagem          66.23          31.57            94      0

In [269]:
#Exibi as 5 ultimas
df.tail()

    id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
35           36  Usinagem          68.47          36.87            87      0
36           37  Inspeção          75.62          30.78           125      1
37           38  Usinagem          78.50          36.39            90      0
38           39  Montagem          76.19          36.54           111      1
39           40  Montagem          68.64          34.88           102      0

In [270]:
#Exibe as 40 linhas e as 6 linhas/ Exibe as dimensões do dataset
df.shape

(40, 6)

In [271]:
#Exibe as informações gerais da base de dados
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_registro    40 non-null     int64
 1   setor          40 non-null     str
 2   temperatura_c  40 non-null     float64
 3   tempo_ciclo_s  40 non-null     float64
 4   producao_dia   40 non-null     int64
 5   falha          40 non-null     int64
dtypes: float64(2), int64(3), str(1)
memory usage: 2.0 KB

In [272]:
#Exibe as colunas
df.columns

Index(['id_registro', 'setor', 'temperatura_c', 'tempo_ciclo_s',
       'producao_dia', 'falha'],
      dtype='str')

In [273]:
#Realiza as contagem de valores nulos
df.isna().sum()

id_registro      0
setor            0
temperatura_c    0
tempo_ciclo_s    0
producao_dia     0
falha            0
dtype: int64

In [274]:
#Valores não nulos
df.notnull().sum()

id_registro      40
setor            40
temperatura_c    40
tempo_ciclo_s    40
producao_dia     40
falha            40
dtype: int64

In [275]:
#Filtrar por coluna 
df["id_registro"]

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
30    31
31    32
32    33
33    34
34    35
35    36
36    37
37    38
38    39
39    40
Name: id_registro, dtype: int64

In [276]:
#Combinando colunas 
df[["temperatura_c","falha", "id_registro"]]

    temperatura_c  falha  id_registro
0           72.62      0            1
1           81.65      0            2
2           68.87      0            3
3           66.84      0            4
4           66.23      0            5
5           64.79      0            6
6           85.02      1            7
7           60.31      0            8
8           75.84      0            9
9           68.38      1           10
10          76.31      0           11
11          74.79      0           12
12          76.31      0           13
13          63.28      0           14
14          64.98      0           15
15          81.48      0           16
16          79.62      1           17
17          69.80      0           18
18          77.16      0           19
19          73.30      1           20
20          79.77      0           21
21          71.76      0           22
22          74.16      0           23
23          74.69      1           24
24          74.03      1           25
25          75.96      0           26
26          60.80      0           27
27          69.37      1           28
28          70.28      0           29
29          73.53      0           30
30          63.59      1           31
31          68.91      0           32
32          77.62      1           33
33          73.32      1           34
34          78.24      0           35
35          68.47      0           36
36          75.62      1           37
37          78.50      0           38
38          76.19      1           39
39          68.64      0           40

In [277]:
df.describe()

       id_registro  temperatura_c  tempo_ciclo_s  producao_dia      falha
count    40.000000      40.000000      40.000000     40.000000  40.000000
mean     20.500000      72.525750      35.103250    116.400000   0.300000
std      11.690452       5.923691       3.918479     26.071696   0.464095
min       1.000000      60.310000      27.200000     80.000000   0.000000
25%      10.750000      68.597500      32.580000     92.750000   0.000000
50%      20.500000      73.425000      34.960000    111.000000   0.000000
75%      30.250000      76.310000      36.925000    136.750000   1.000000
max      40.000000      85.020000      47.450000    159.000000   1.000000

In [278]:
#Comando para visualizar as colunas em formas de listas 
df.columns.to_list()

['id_registro',
 'setor',
 'temperatura_c',
 'tempo_ciclo_s',
 'producao_dia',
 'falha']

#  Exercicio
- Importem a bibliotecas pandas
- Exibir as 5 primeiros dados 
- Exibir os 5 ultimos dados
- Realizar a leitura dos dados 
- Exibir a quantdade de linhas e colunas
- Exibir as informações gerais dessa base de dados
- Realizar a contagem de valores não nulos
- Exibir os nomes das colunas 
- Exibir a descrição (min,max mean,std, quartis)

In [279]:
df = pd.read_csv(r".\data\dataset_aula01_techshop_vendas.csv")

In [280]:
#Realizar as leituras 
df

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
0,2024-01-01,Acessórios,36.20,1,Sudeste,Instagram,3.3
1,2024-01-01,Acessórios,122.61,5,Sudeste,Orgânico,4.4
2,2024-01-02,Acessórios,151.19,4,Sul,Google Ads,4.6
3,2024-01-03,TVs,3399.16,2,Sudeste,Google Ads,4.1
4,2024-01-04,Smartphones,3180.94,2,Nordeste,Instagram,3.9
...,...,...,...,...,...,...,...
795,2024-12-27,Áudio,1128.44,4,Sul,Orgânico,4.6
796,2024-12-27,Acessórios,209.29,4,Sudeste,Google Ads,3.8
797,2024-12-28,Notebooks,7979.84,2,Sudeste,Google Ads,4.4
798,2024-12-28,Notebooks,4168.01,1,Nordeste,Instagram,4.1
799,2024-12-28,Acessórios,111.95,1,Sul,Google Ads,4.7

In [281]:
#Os primeiros 5 
df.head()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
0,2024-01-01,Acessórios,36.20,1,Sudeste,Instagram,3.3
1,2024-01-01,Acessórios,122.61,5,Sudeste,Orgânico,4.4
2,2024-01-02,Acessórios,151.19,4,Sul,Google Ads,4.6
3,2024-01-03,TVs,3399.16,2,Sudeste,Google Ads,4.1
4,2024-01-04,Smartphones,3180.94,2,Nordeste,Instagram,3.9

In [282]:
#Os 5 ultimos 
df.tail()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
795,2024-12-27,Áudio,1128.44,4,Sul,Orgânico,4.6
796,2024-12-27,Acessórios,209.29,4,Sudeste,Google Ads,3.8
797,2024-12-28,Notebooks,7979.84,2,Sudeste,Google Ads,4.4
798,2024-12-28,Notebooks,4168.01,1,Nordeste,Instagram,4.1
799,2024-12-28,Acessórios,111.95,1,Sul,Google Ads,4.7

In [283]:
#Exibir as quantidades de colunas e linhas 
df.shape

(800, 7)

In [284]:
#Informações gerais da base de dados
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_pedido      800 non-null    str
 1   categoria        800 non-null    str
 2   preco_unitario   800 non-null    float64
 3   quantidade       800 non-null    int64
 4   regiao           800 non-null    str
 5   canal_marketing  800 non-null    str
 6   avaliacao        800 non-null    float64
dtypes: float64(2), int64(1), str(4)
memory usage: 43.9 KB

In [285]:
#Contagem de valores não nulos
df.notnull().sum

<bound method DataFrame.sum of      data_pedido  categoria  preco_unitario  quantidade  regiao  \
0           True       True            True        True    True
1           True       True            True        True    True
2           True       True            True        True    True
3           True       True            True        True    True
4           True       True            True        True    True
..           ...        ...             ...         ...     ...
795         True       True            True        True    True
796         True       True            True        True    True
797         True       True            True        True    True
798         True       True            True        True    True
799         True       True            True        True    True

     canal_marketing  avaliacao
0               True       True
1               True       True
2               True       True
3               True       True
4               True       True
..               ...        ...
795             True       True
796             True       True
797             True       True
798             True       True
799             True       True

[800 rows x 7 columns]>

In [286]:
#Nome das colunas 
df.columns.to_list()

['data_pedido',
 'categoria',
 'preco_unitario',
 'quantidade',
 'regiao',
 'canal_marketing',
 'avaliacao']

In [287]:
#Descrição da base de dados
df.describe()

       preco_unitario  quantidade   avaliacao
count      800.000000  800.000000  800.000000
mean      2173.764038    2.237500    4.165500
std       2042.173946    1.306034    0.542658
min         20.070000    1.000000    2.400000
25%        249.837500    1.000000    3.800000
50%       1458.565000    2.000000    4.200000
75%       3707.427500    3.000000    4.600000
max       7979.840000    5.000000    5.000000

In [288]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_pedido      800 non-null    str
 1   categoria        800 non-null    str
 2   preco_unitario   800 non-null    float64
 3   quantidade       800 non-null    int64
 4   regiao           800 non-null    str
 5   canal_marketing  800 non-null    str
 6   avaliacao        800 non-null    float64
dtypes: float64(2), int64(1), str(4)
memory usage: 43.9 KB

In [289]:
df["faturamento"] = df["preco_unitario"] * df["quantidade"]
df["faturamento"]

0         36.20
1        613.05
2        604.76
3       6798.32
4       6361.88
         ...
795     4513.76
796      837.16
797    15959.68
798     4168.01
799      111.95
Name: faturamento, Length: 800, dtype: float64

In [290]:
df_tratado = pd.read_csv(r".\data\dataset_aula01_techshop_vendas.csv", parse_dates=["data_pedido"])
df_tratado.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_pedido      800 non-null    datetime64[us]
 1   categoria        800 non-null    str
 2   preco_unitario   800 non-null    float64
 3   quantidade       800 non-null    int64
 4   regiao           800 non-null    str
 5   canal_marketing  800 non-null    str
 6   avaliacao        800 non-null    float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 43.9 KB

In [291]:
df_tratado["faturamento"] = df_tratado["preco_unitario"] * df_tratado["quantidade"]
df_tratado["faturamento"]

0         36.20
1        613.05
2        604.76
3       6798.32
4       6361.88
         ...
795     4513.76
796      837.16
797    15959.68
798     4168.01
799      111.95
Name: faturamento, Length: 800, dtype: float64

In [292]:
df_tratado

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao,faturamento
0,2024-01-01,Acessórios,36.20,1,Sudeste,Instagram,3.3,36.20
1,2024-01-01,Acessórios,122.61,5,Sudeste,Orgânico,4.4,613.05
2,2024-01-02,Acessórios,151.19,4,Sul,Google Ads,4.6,604.76
3,2024-01-03,TVs,3399.16,2,Sudeste,Google Ads,4.1,6798.32
4,2024-01-04,Smartphones,3180.94,2,Nordeste,Instagram,3.9,6361.88
...,...,...,...,...,...,...,...,...
795,2024-12-27,Áudio,1128.44,4,Sul,Orgânico,4.6,4513.76
796,2024-12-27,Acessórios,209.29,4,Sudeste,Google Ads,3.8,837.16
797,2024-12-28,Notebooks,7979.84,2,Sudeste,Google Ads,4.4,15959.68
798,2024-12-28,Notebooks,4168.01,1,Nordeste,Instagram,4.1,4168.01
799,2024-12-28,Acessórios,111.95,1,Sul,Google Ads,4.7,111.95

In [293]:
df_tratado.tail

<bound method NDFrame.tail of     data_pedido    categoria  preco_unitario  quantidade    regiao  \
0    2024-01-01   Acessórios           36.20           1   Sudeste
1    2024-01-01   Acessórios          122.61           5   Sudeste
2    2024-01-02   Acessórios          151.19           4       Sul
3    2024-01-03          TVs         3399.16           2   Sudeste
4    2024-01-04  Smartphones         3180.94           2  Nordeste
..          ...          ...             ...         ...       ...
795  2024-12-27        Áudio         1128.44           4       Sul
796  2024-12-27   Acessórios          209.29           4   Sudeste
797  2024-12-28    Notebooks         7979.84           2   Sudeste
798  2024-12-28    Notebooks         4168.01           1  Nordeste
799  2024-12-28   Acessórios          111.95           1       Sul

    canal_marketing  avaliacao  faturamento
0         Instagram        3.3        36.20
1          Orgânico        4.4       613.05
2        Google Ads        4.6       604.76
3        Google Ads        4.1      6798.32
4         Instagram        3.9      6361.88
..              ...        ...          ...
795        Orgânico        4.6      4513.76
796      Google Ads        3.8       837.16
797      Google Ads        4.4     15959.68
798       Instagram        4.1      4168.01
799      Google Ads        4.7       111.95

[800 rows x 8 columns]>

In [294]:
df_tratado.head

<bound method NDFrame.head of     data_pedido    categoria  preco_unitario  quantidade    regiao  \
0    2024-01-01   Acessórios           36.20           1   Sudeste
1    2024-01-01   Acessórios          122.61           5   Sudeste
2    2024-01-02   Acessórios          151.19           4       Sul
3    2024-01-03          TVs         3399.16           2   Sudeste
4    2024-01-04  Smartphones         3180.94           2  Nordeste
..          ...          ...             ...         ...       ...
795  2024-12-27        Áudio         1128.44           4       Sul
796  2024-12-27   Acessórios          209.29           4   Sudeste
797  2024-12-28    Notebooks         7979.84           2   Sudeste
798  2024-12-28    Notebooks         4168.01           1  Nordeste
799  2024-12-28   Acessórios          111.95           1       Sul

    canal_marketing  avaliacao  faturamento
0         Instagram        3.3        36.20
1          Orgânico        4.4       613.05
2        Google Ads        4.6       604.76
3        Google Ads        4.1      6798.32
4         Instagram        3.9      6361.88
..              ...        ...          ...
795        Orgânico        4.6      4513.76
796      Google Ads        3.8       837.16
797      Google Ads        4.4     15959.68
798       Instagram        4.1      4168.01
799      Google Ads        4.7       111.95

[800 rows x 8 columns]>

In [295]:
df_tratado.shape

(800, 8)

In [296]:
df_tratado.describe()

,data_pedido,preco_unitario,quantidade,avaliacao,faturamento
count,800,800.000000,800.000000,800.000000,800.000000
mean,2024-07-28 03:07:12,2173.764038,2.237500,4.165500,3559.530162
min,2024-01-01 00:00:00,20.070000,1.000000,2.400000,27.340000
25%,2024-05-02 00:00:00,249.837500,1.000000,3.800000,750.622500
50%,2024-08-10 00:00:00,1458.565000,2.000000,4.200000,2800.915000
75%,2024-11-04 06:00:00,3707.427500,3.000000,4.600000,5441.440000
max,2024-12-28 00:00:00,7979.840000,5.000000,5.000000,15959.680000
std,NaN,2042.173946,1.306034,0.542658,3296.992462

In [297]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_pedido      800 non-null    str
 1   categoria        800 non-null    str
 2   preco_unitario   800 non-null    float64
 3   quantidade       800 non-null    int64
 4   regiao           800 non-null    str
 5   canal_marketing  800 non-null    str
 6   avaliacao        800 non-null    float64
 7   faturamento      800 non-null    float64
dtypes: float64(3), int64(1), str(4)
memory usage: 50.1 KB

In [298]:
faturamento_total = df_tratado["faturamento"].sum()
print(faturamento_total)

2847624.13

In [299]:
faturamento_correto = f"{faturamento_total:,.2f}".replace(",","x").replace(".",",").replace("x",".")
print(faturamento_correto)

2.847.624,13

In [300]:
df_tratado.groupby("categoria")["faturamento"].sum()

categoria
Acessórios     103851.41
Notebooks      922453.90
Smartphones    970236.71
TVs            463526.50
Áudio          387555.61
Name: faturamento, dtype: float64

In [301]:
df_tratado.groupby("categoria")["faturamento"].sum().sort_values

<bound method Series.sort_values of categoria
Acessórios     103851.41
Notebooks      922453.90
Smartphones    970236.71
TVs            463526.50
Áudio          387555.61
Name: faturamento, dtype: float64>

In [308]:
df_tratado.groupby("regiao")["faturamento"].sum()

regiao
Centro-Oeste     313101.36
Nordeste         548131.32
Norte            188452.12
Sudeste         1288280.26
Sul              509659.07
Name: faturamento, dtype: float64

In [309]:
df_tratado.loc["local"] = df_tratado["faturamento"].sum()
df_tratado.tail

<bound method NDFrame.tail of                data_pedido    categoria  preco_unitario  quantidade  \
0      2024-01-01 00:00:00   Acessórios           36.20        1.00
1      2024-01-01 00:00:00   Acessórios          122.61        5.00
2      2024-01-02 00:00:00   Acessórios          151.19        4.00
3      2024-01-03 00:00:00          TVs         3399.16        2.00
4      2024-01-04 00:00:00  Smartphones         3180.94        2.00
...                    ...          ...             ...         ...
796    2024-12-27 00:00:00   Acessórios          209.29        4.00
797    2024-12-28 00:00:00    Notebooks         7979.84        2.00
798    2024-12-28 00:00:00    Notebooks         4168.01        1.00
799    2024-12-28 00:00:00   Acessórios          111.95        1.00
local           2847624.13   2847624.13      2847624.13  2847624.13

           regiao canal_marketing   avaliacao  faturamento
0         Sudeste       Instagram        3.30        36.20
1         Sudeste        Orgânico        4.40       613.05
2             Sul      Google Ads        4.60       604.76
3         Sudeste      Google Ads        4.10      6798.32
4        Nordeste       Instagram        3.90      6361.88
...           ...             ...         ...          ...
796       Sudeste      Google Ads        3.80       837.16
797       Sudeste      Google Ads        4.40     15959.68
798      Nordeste       Instagram        4.10      4168.01
799           Sul      Google Ads        4.70       111.95
local  2847624.13      2847624.13  2847624.13   2847624.13

[801 rows x 8 columns]>

In [304]:
def converter(valor):
    return f"{valor:,.2f}".replace(",","x").replace(".",",").replace("x",".")

In [311]:
agrupamento_faturamento_regiao = df_tratado.groupby("regiao")["faturamento"].sum()
agrupamento_faturamento_regiao.map(converter)

regiao
2847624.13      2.847.624,13
Centro-Oeste      313.101,36
Nordeste          548.131,32
Norte             188.452,12
Sudeste         1.288.280,26
Sul               509.659,07
Name: faturamento, dtype: str

In [ ]:
#Gera uma cópia do df_tratado para o df original
df = df_tratado.copy()

In [ ]:
#Gera o arquivo tratado dentro da pasta 
df.to_csv("dataset_tratado.csv")