In [78]:
conceito de n-gramas

SyntaxError: invalid syntax (1311432796.py, line 1)

In [79]:
frase = "O amor é lindo o amor é forte o amor vence tudo"

In [80]:
palavras = frase.split()
palavras

['O',
 'amor',
 'é',
 'lindo',
 'o',
 'amor',
 'é',
 'forte',
 'o',
 'amor',
 'vence',
 'tudo']

In [81]:
import pandas as pd
tabela = pd.DataFrame({"palavra":palavras})
tabela

   palavra
0        O
1     amor
2        é
3    lindo
4        o
5     amor
6        é
7    forte
8        o
9     amor
10   vence
11    tudo

In [82]:
tabela["proxima_palavra"] = tabela["palavra"].shift(-1)
tabela

   palavra proxima_palavra
0        O            amor
1     amor               é
2        é           lindo
3    lindo               o
4        o            amor
5     amor               é
6        é           forte
7    forte               o
8        o            amor
9     amor           vence
10   vence            tudo
11    tudo             NaN

In [83]:
tabela = tabela.dropna()
tabela

   palavra proxima_palavra
0        O            amor
1     amor               é
2        é           lindo
3    lindo               o
4        o            amor
5     amor               é
6        é           forte
7    forte               o
8        o            amor
9     amor           vence
10   vence            tudo

In [96]:
filtro = tabela["palavra"] == "o"
tabela[filtro]

  palavra proxima_palavra
4       o            amor
8       o            amor

In [97]:
tabela[filtro]["proxima_palavra"].value_counts(normalize=True)

proxima_palavra
amor    1.0
Name: proportion, dtype: float64

In [98]:
tabela[filtro]["proxima_palavra"].value_counts().idxmax()

'amor'